### PR TITLE
Reform new punctuation marks for personal identity codes. Increase pe…

### PR DESCRIPTION
**Pull request by kallesuomala**
…rson number range

### CODE REVIEW

**Comment by alexhanh** [comment]
From https://dvv.fi/en/reform-of-personal-identity-code

`From the beginning of 2027, gender would no longer be determinable from the identification number of the personal identity code. In the personal identity code, the individual number is the three-digit number following the punctuation mark, which is currently an even number for women and an odd number for men. For personal identity codes issued after the change, the number would be random.`

I know this is several years from now, but the gender related methods should probably do a safe check whether a person was born before 1.1.2017 or raise an exception otherwise when accessed.

Also `The current personal identity codes will not be voided, which means that the personal identity codes that have already been granted, would remain unchanged.`

Does the new system need to take backwards compatibility somehow into account or not? And on the other hand, only allow the new punctuation marks etc. for people born after certain time?

As the possibilities get more complex, perhaps it would be wise to add some tests for edge cases the very least.

We welcome any feedback @vesan

**Comment by kallesuomala** [comment]
@alexhanh Starting 2027 the gender related methods will no longer be reliable, since we don't have a reference for the date that the identity number was issued. Starting 2027 the person number that currently is defined by gender will be random even for people born before 2027, if the number was issued after the change (immigrants for example). Same goes for the punctuation marks.

The current changes support the old punctuation marks and adds the new ones for people born in the 20th and 21st centuries. I will add some tests for the changes.

**Comment by alexhanh** [comment]
@kallesuomala Doesn't `For personal identity codes issued after the [2027] change, the number would be random.` mean exactly that the gender methods are unreliable with pins issued after 1.1.2017, but the gender would still be identifiable from the old ones? Also I don't see where it is mentioned that the date of birth would be hidden after 1.1.2017 for old or new ones?

It clearly says on the page that `The current personal identity codes will not be voided, which means that the personal identity codes that have already been granted, would remain unchanged.`.

Please correct me if I'm misunderstanding something.

**Comment by kallesuomala** [comment]
@alexhanh My concern was that the birth date is not always the same as the date of issue. I think people immigrating to Finland at an older age also get issued personal identity codes.

Since the old punctuation is replaced next year we can still use the gender methods for the codes with old punctuation marks. They could be used for all codes issued before 1.1.2023. I can add a check for that.

**Comment by alexhanh** [comment]
@kallesuomala Ahh, now I understand your concern.

I think this is something that should be confirmed directly from DVV. I didn't find any information that they would use the issuance date instead of actual birthday for the pin in case of immigrants / foreigners.

My bet is that they will use the birthday for foreigners, since they don't mention at all that they would obfuscate the birthday (they do mention gender tho).

But yeah, should probably be confirmed.

**Comment by kallesuomala** [comment]
@alexhanh They would not use the issuance date instead of the birthday for the pin. The pin always starts with the birth date. My point is that we can't use the birthdate as a reference for wether the identity code is gender neutral or not. Example: Someone born in 01.01.1993 immigrates to Finland in 2028. The pin could start with 010193B and the remaining part would be random (gender neutral) because it was issued in 2028. The person was born before 2027 but the identity code is gender neutral, therefore checking the birthday is not a reliable indicator of gender neutralness.

Like I mentioned earlier the changes to punctuation will be made before the codes become gender neutral. We can be certain that the codes using old punctuation are gender specific. I suggest we use the punctuation mark for filtering gender neutral pins. There is no mention of the pins changing in any way for the 2027 update (except the person number being random, but there is no way to distinguish random numbers from predifined ones.).

**Comment by alexhanh** [comment]
@kallesuomala Thx for drilling the point home, you are absolutely right. I have no further objections, except for the test coverage and making the gender related methods available for backwards compatibility while reducing the risk that they are misused. :thumbsup:

**Comment by kallesuomala** [comment]
@alexhanh Added a method to check for gender neutralness. An exception is raised if gender methods are used for gender neutral pins starting 2027. Added some test coverage for the changes I made. That should be all.

**Comment by alexhanh** [comment]
@kallesuomala Looks good to me. Want to go ahead and merge?

**Comment by kallesuomala** [comment]
@alexhanh The new version should probably be updated to rubygems as well. Looks like you are the only owner so would you like to go ahead and `rake release`?

**Comment by alexhanh** [comment]
@kallesuomala Ah good catch. Can you send your and Niko's Rubygems accounts, so I can add you guys as owners?

**Pull request merged**
